# Generated by Django 4.2.3 on 2023-08-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(blank=True, max_length=20, null=True)),
                ('c_description', models.CharField(blank=True, max_length=20, null=True)),
                ('c_img', models.ImageField(blank=True, null=True, upload_to='category')),
            ],
        ),
    ]
