# Generated by Django 4.2.3 on 2023-08-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_category', models.CharField(blank=True, max_length=20, null=True)),
                ('b_name', models.CharField(blank=True, max_length=20, null=True)),
                ('b_price', models.IntegerField(blank=True, null=True)),
                ('b_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('b_auther', models.CharField(blank=True, max_length=20, null=True)),
                ('b_auth_desc', models.CharField(blank=True, max_length=1000, null=True)),
                ('b_cover', models.ImageField(blank=True, null=True, upload_to='Books')),
            ],
        ),
    ]
