# Generated by Django 4.2.3 on 2023-08-09 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_bookdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomeBk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_nme', models.CharField(blank=True, max_length=20, null=True)),
                ('bk_des', models.CharField(blank=True, max_length=500, null=True)),
                ('bk_cov', models.ImageField(blank=True, null=True, upload_to='upcomebk')),
            ],
        ),
    ]
