# Generated by Django 4.2.3 on 2023-08-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(blank=True, max_length=50, null=True)),
                ('EmailId', models.EmailField(blank=True, max_length=50, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('PassWord', models.CharField(blank=True, max_length=50, null=True)),
                ('UserImage', models.ImageField(blank=True, null=True, upload_to='UserProfile')),
            ],
        ),
    ]
