# Generated by Django 4.2.3 on 2023-08-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webbooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=20, null=True)),
                ('pro_name', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
