# Generated by Django 4.2.3 on 2023-08-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webbooks', '0002_cartdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('State', models.CharField(blank=True, max_length=20, null=True)),
                ('zip', models.IntegerField(blank=True, null=True)),
                ('c_name', models.CharField(blank=True, max_length=20, null=True)),
                ('c_number', models.IntegerField(blank=True, null=True)),
                ('exp_month', models.CharField(blank=True, max_length=20, null=True)),
                ('exp_yer', models.IntegerField(blank=True, null=True)),
                ('cvv', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
