# Generated by Django 4.2.3 on 2023-08-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webbooks', '0003_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('desc', models.IntegerField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('emails', models.CharField(blank=True, max_length=20, null=True)),
                ('t_rate', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
