# Generated by Django 4.2.3 on 2023-08-07 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webbooks', '0005_alter_rate_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='name',
        ),
    ]
