# Generated by Django 4.2.3 on 2023-08-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webbooks', '0006_remove_rate_emails_remove_rate_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='t_rate',
        ),
    ]
