# Generated by Django 4.2.3 on 2023-08-07 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webbooks', '0007_remove_rate_t_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
