# Generated by Django 4.2.3 on 2023-08-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webbooks', '0008_delete_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='Qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartdb',
            name='aut_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
