# Generated by Django 4.2.3 on 2023-08-10 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_upcomebk'),
        ('Webbooks', '0009_cartdb_qty_cartdb_aut_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('rate', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.bookdb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webbooks.userdb')),
            ],
        ),
    ]
