# Generated by Django 4.2.3 on 2023-08-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webbooks', '0010_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
