# Generated by Django 4.2.3 on 2023-08-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webbooks', '0011_alter_review_comment_alter_review_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
